FROM python:3.12-slim

WORKDIR /app

COPY services/scheduler/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY pkg /app/pkg
COPY services /app/services

CMD ["python", "-m", "services.scheduler.main"]
