apiVersion: v1
kind: Pod
metadata:
  name: qos-best-effort
  namespace: default
  labels:
    app: qos-best-effort
spec:
  containers:
    - name: stress
      image: polinux/stress
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "300M", "--vm-hang", "1"]
